### ISSUE TITLE
Amplify Mocking & Testing doesn't work just setting with "npx amplify-app@latest"

### ISSUE THREAD

**Issue by geoseong** [geoseong/study-amplify-with-react-native#2]
When I do
`$ amplify mock`

that happens
```sh
{ UndeterminedEnvironmentError: Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
    at AmplifyToolkit.getEnvInfo [as _getEnvInfo] (/Users/geoseong/.npm-packages/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-env-info.js:19:15)
    at Object.getMockDataDirectory (/Users/geoseong/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/utils/mock-data-directory.js:5:45)
    at Object.addMockDataToGitIgnore (/Users/geoseong/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/utils/git-ignore.js:10:80)
    at Object.<anonymous> (/Users/geoseong/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/index.js:18:21)
    at Generator.next (<anonymous>)
    at /Users/geoseong/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/geoseong/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/index.js:4:12)
    at Object.start (/Users/geoseong/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/index.js:15:12)
    at Object.<anonymous> (/Users/geoseong/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/mockAll.js:41:43) name: 'UndeterminedEnvironmentError' }
[1]    50171 terminated  amplify mock
FAIL: 143
```

**Comment by geoseong** [comment]
should initialize amplify project
do
$ amplify init
